export const RECIEVE_LIST = 'RECIEVE_LIST';
export const RECOVER_CART = 'RECOVER_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CNAHGE_ITEM_QUANTITY = 'CNAHGE_ITEM_QUANTITY';
